# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Gather service facts
  ansible.builtin.service_facts:

- name: Open Redis port on FirewallD Public Zone
  ansible.posix.firewalld:
    port: "{{ redis_port }}/tcp"
    permanent: true
    state: enabled
    zone: public
    immediate: true
  when:
    - ansible_facts.services["firewalld.service"] is defined
    - ansible_facts.services["firewalld.service"].state == "running"
    - ansible_facts.services["firewalld.service"].status == "enabled"

- name: Create Redis systemd file
  ansible.builtin.template:
    src: redis.service.j2
    dest: /usr/lib/systemd/system/redis.service
    owner: root
    group: root
    mode: "0644"

# Refer to the redis defaults and Redis Guide for an explanation of the replica priority
- name: Calculate replica priority
  ansible.builtin.set_fact:
    redis_replica_priority_final: >-
      {%- if redis_replica_priority != 'auto' -%}
        {{ redis_replica_priority }}
      {%- elif redis_is_master_node -%}
        10
      {%- elif redis_is_replica_node -%}
        {{ 50 + (groups['redis_replica'].index(inventory_hostname) * 50) }}
      {%- else -%}
        100
      {%- endif -%}

- name: Validate replica priority
  ansible.builtin.assert:
    that:
      - redis_replica_priority_final | int >= 0
      - redis_replica_priority_final | int <= 255
    fail_msg: "redis_replica_priority must be between 0-255, got {{ redis_replica_priority_final }}"

- name: Calculate Redis maxmemory automatically
  ansible.builtin.set_fact:
    redis_maxmemory_bytes: >-
      {{
        (
          [
            redis_maxmemory_min_mb | int,
            (
              (ansible_facts.memtotal_mb | int)
              * (redis_maxmemory_ratio | float)
            ) | int
          ] | max
        ) * 1024 * 1024
      }}
  when: redis_maxmemory_bytes == "auto"
  tags: configure_redis

- name: Use template to generate redis.conf
  ansible.builtin.template:
    src: redis.conf.j2
    dest: "{{ redis_conf_file }}"
    owner: "{{ redis_owner }}"
    group: "{{ redis_group }}"
    mode: "0640"
    setype: redis_conf_t
    backup: true
  tags: configure_redis

- name: Deploy logrotate config for Redis
  ansible.builtin.template:
    src: redis.logrotate.j2
    dest: /etc/logrotate.d/redis
    owner: root
    group: root
    mode: '0644'
