# Copyright (c) 2026, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---

- name: Verify Redis Hardware Requirements
  ansible.builtin.import_tasks: ../../common/tasks/verify-component-hardware.yml
  vars:
    component_name: "Redis"
    hw_specs_var_name: "redis_hw_specs"
    invalid_platform_release_var: "redis_invalid_platform_release"

# Any mongo specific verifications go here...
