# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Configure SELinux
  tags: configure_selinux
  when: ansible_selinux.status == "enabled"
  block:
    - name: SELinux - Configure file context when using non-standard bin directory
      ansible.builtin.include_role:
        name: selinux
        tasks_from: configure-context
      vars:
        selinux_target: "{{ gateway_python_venv }}/bin(/.*)?"
        selinux_setype: bin_t
        selinux_path: "{{ gateway_python_venv }}/bin"
      when: not (gateway_python_venv.startswith('/opt/') or gateway_python_venv.startswith('/usr/'))

    - name: SELinux - Configure file context when using non-standard data directory
      ansible.builtin.include_role:
        name: selinux
        tasks_from: configure-context
      vars:
        selinux_target: "{{ gateway_data_dir }}(/.*)?"
        selinux_setype: var_lib_t
        selinux_path: "{{ gateway_data_dir }}"
      when: not gateway_data_dir.startswith('/var/lib/')

    - name: SELinux - Configure file context when using non-standard log directory
      ansible.builtin.include_role:
        name: selinux
        tasks_from: configure-context
      vars:
        selinux_target: "{{ gateway_log_dir }}(/.*)?"
        selinux_setype: var_log_t
        selinux_path: "{{ gateway_log_dir }}"
      when: not gateway_log_dir.startswith('/var/log/')

    - name: Allow IAG to listen on tcp port {{ gateway_port }}
      community.general.seport:
        ports: "{{ gateway_port }}"
        proto: tcp
        setype: http_port_t
        state: present
