# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Prepare MongoDB PKI infrastructure
  when: mongodb_tls_copy_certs | bool
  tags:
    - mongodb
    - mongodb_certificates
    - certificates
  block:
    - name: Create MongoDB PKI base directory
      ansible.builtin.file:
        state: directory
        path: "{{ mongodb_pki_base_dir }}"
        owner: "{{ mongodb_owner }}"
        group: "{{ mongodb_group }}"
        mode: "0750"

    - name: Create MongoDB private directory
      ansible.builtin.file:
        state: directory
        path: "{{ mongodb_pki_private_dir }}"
        owner: "{{ mongodb_owner }}"
        group: "{{ mongodb_group }}"
        mode: "0700"

    - name: Copy Gateway certificates
      ansible.builtin.include_tasks:
        file: copy-certs.yml

- name: Create MongoDB config file (TLS)
  ansible.builtin.template:
    src: mongod.conf.j2
    dest: "{{ mongodb_conf_file }}"
    owner: "{{ mongodb_owner }}"
    group: "{{ mongodb_group }}"
    mode: "0644"
  vars:
    stage: "tls"
  notify: restart mongod
  tags:
    - mongodb
    - mongodb_config

- name: Flush handlers to restart mongod with TLS config
  ansible.builtin.meta: flush_handlers
  tags:
    - mongodb
    - mongodb_certificates
    - certificates
