# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
# ============================================================================
# CyberArk Central Credential Provider (CCP) - Used only when platform_secret_provider_name
# is set to 'CyberArkCcp'
# ============================================================================

# The URL to the CyberArk Central Credential Provider.
platform_cyberark_url:

# Specifies the unique ID of the application issuing the password request to CyberArk CCP.
platform_cyberark_app_id:

# If true, disables the validation checks for TLS certificates and allows the use of invalid
# or self-signed certificates to connect.
platform_cyberark_allow_invalid_certificates:

# The .pem file that contains the root certificate chain from the Certificate Authority.
# Specify the file name of the .pem file using absolute paths.
platform_cyberark_ca:

# The certificate key file location. Specify the location of the key file using absolute paths.
platform_cyberark_key:

# The .pem file that contains the client certificate. Specify the file name of the .pem file
# using absolute paths.
platform_cyberark_certificate:

# String representation of the PEM-encoded root certificate chain from the Certificate
# Authority. Alternative to platform_cyberark_ca when the CA contents should be inlined.
platform_cyberark_ca_contents:

# String representation of the PEM-encoded certificate key. Alternative to platform_cyberark_key
# when the key contents should be inlined.
platform_cyberark_key_contents:

# String representation of the PEM-encoded client certificate. Alternative to
# platform_cyberark_certificate when the certificate contents should be inlined.
platform_cyberark_certificate_contents:

# The number of seconds that the Central Credential Provider will try to retrieve the secret
# value.
platform_cyberark_connection_timeout:

# Set this property to the reason for retrieving the password to have the reason text appear
# in CyberArk Credential Provider's audit log.
platform_cyberark_reason_text:
