# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
# Name of the secrets provider. Required for CyberArk CCP. Not required for Hashicorp Vault.
# Valid values: CyberArkCcp, HashicorpVault
platform_secret_provider_name:
