# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
# A toggle to instruct the webserver to include HTTP cache control headers on the response.
platform_webserver_cache_control_enabled:

# Timeout to use for incoming HTTP requests to the platform API, in milliseconds.
platform_webserver_timeout:

# The value of the HTTP Access-Control-Allow-Origin header returned to clients.
platform_webserver_response_header_access_control_allow_origin:

# If true, allows the webserver to respond to insecure HTTP requests.
platform_webserver_http_enabled: true

# The port on which the webserver listens for HTTP requests.
platform_webserver_http_port: 3000

# If true, allows the webserver to respond to secure HTTPS requests.
platform_webserver_https_enabled: true

# The port on which the webserver listens for HTTPS requests.
platform_webserver_https_port: 3443

# The passphrase for the private key used to enable TLS sessions.
platform_webserver_https_passphrase:

# The set of allowed SSL/TLS protocol versions.
platform_webserver_https_secure_protocol: TLS_method

# The allowed SSL/TLS cipher suite.
platform_webserver_https_ciphers:

# Specifies the number of renegotiations that are allowed in a single HTTPS connection.
platform_webserver_https_client_reneg_limit:

# Specifies the time renegotiation window in seconds for a single HTTPS connection.
platform_webserver_https_client_reneg_window:

# The set of allowed HTTP verbs in addition to those defined in the standard HTTP/1.1 protocol.
platform_webserver_http_allowed_optional_verbs:
