# Copyright (c) 2026, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---

- name: Verify Platform Hardware Requirements
  ansible.builtin.import_tasks: ../../common/tasks/verify-component-hardware.yml
  vars:
    component_name: "Platform"
    hw_specs_var_name: "platform_hw_specs"
    invalid_platform_release_var: "platform_invalid_release"

# Any platform specific verifications go here...
