{
 "title": "Redis",
 "description": "Redis dashboard tracking common metrics",
 "tags": [ "Redis" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Redis CPU User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "redis_cpu_user_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Redis CPU Sys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "redis_cpu_sys_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Redis Memory Used",
   "type": "timeseries",
   "description": "Memory used",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "redis_memory_used_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Redis Total Commands",
   "type": "timeseries",
   "description": "Total number of calls per command",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "redis_commands_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Redis Failed Commands",
   "type": "timeseries",
   "description": "Total number of errors prior command execution per command",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "redis_commands_failed_calls_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Commands Duration",
   "type": "timeseries",
   "description": "Total amount of time in seconds spent per command",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "redis_commands_duration_seconds_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Expiring Keys",
   "type": "gauge",
   "description": "Total number of expiring keys by DB",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_db_keys_expiring{db=\"db0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Uptime",
   "type": "gauge",
   "description": "Redis uptime in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_uptime_in_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Redis Connected Secondaries",
   "type": "gauge",
   "description": "The number of connected secondaries to the Redis primary",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_connected_slaves", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Redis Connected Clients",
   "type": "gauge",
   "description": "The number of current connected Redis clients",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_connected_clients", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Redis keys db0",
   "type": "gauge",
   "description": "The number of keys in Redis db0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_db_keys{db=\"db0\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}