{
 "title": "IAP",
 "description": "A dashboard of common IAP metrics to follow",
 "tags": [ "IAP" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "IAP Active User Sessions",
   "type": "timeseries",
   "description": "The number of active user sessions.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "iap_active_sessions", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "IAP Active Jobs",
   "type": "timeseries",
   "description": "The number of active jobs at a given moment. \"Active\" includes running and errored jobs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "iap_active_jobs", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Workflow Engine Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{groupname=\"Pronghorn WorkFlowEngine Application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflow Engine CPU Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "namedprocess_namegroup_cpu_seconds_total{groupname=\"Pronghorn WorkFlowEngine Application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AGManager Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{groupname=\"Pronghorn AGManager Application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IAP CPU system & user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "iap_cpu_system_usage", "legendFormat": "__auto" },
    { "expr": "iap_cpu_user_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Automation Studeo Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{groupname=\"Pronghorn AutomationStudio Application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JSON Forms Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{groupname=\"Pronghorn JsonForms Application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JST Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{groupname=\"Pronghorn Jst Application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MOP Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{groupname=\"Pronghorn MOP Application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NSO Manager Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{groupname=\"Pronghorn NSOManager Application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operations Manager Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{groupname=\"Pronghorn OperationsManager Application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Search Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{groupname=\"Pronghorn Search Application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Template Builder Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{groupname=\"Pronghorn TemplateBuilder Application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IAP Heap used percentage",
   "type": "timeseries",
   "description": "The percentage of the heap memory used",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "iap_memory_heap_used_size", "legendFormat": "__auto" },
    { "expr": "iap_total_memory_heap_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pronghorn Core Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{groupname=\"Pronghorn core\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Configuration Manager Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{groupname=\"Pronghorn ConfigurationManager Application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pronghorn Core CPU Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "namedprocess_namegroup_cpu_seconds_total{groupname=\"Pronghorn core\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}